version: "3.9"
services:
  libraryservice:
    image: libraryrest
    ports:
      - "80:8080"
    links:
      - "postgres:database"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

