logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.jaqg.banking: DEBUG

spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:bank;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password:
    hikari:
      poolName: Hikari
      auto-commit: true
  h2:
    console:
      enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true