CREATE TABLE account(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    balance DECIMAL(10,2)
);

INSERT INTO account (name, balance) VALUES ('Claire', 240.54);
INSERT INTO account(name, balance) VALUES ('Poppy', 4450.99);
